# Generated by Django 2.1.15 on 2021-02-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cierrecaja',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='um',
        ),
        migrations.DeleteModel(
            name='CierreCaja',
        ),
    ]
