# Generated by Django 2.1.15 on 2021-03-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reses', '0002_auto_20210227_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reses.Animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='res',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
