# Generated by Django 2.1.15 on 2021-03-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reses', '0003_auto_20210307_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
