# Generated by Django 2.1.15 on 2021-03-11 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reses', '0004_animal_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaReses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('precio', models.FloatField(default=0)),
                ('medio_pago', models.CharField(choices=[('TB', 'TRANSFERENCIA BANCARIA'), ('MP', 'MERCADO PAGO'), ('EF', 'EFECTIVO'), ('TJ', 'TARJETA')], default='efectivo', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reses.Res')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VentaRes',
                'verbose_name_plural': 'VentaReses',
            },
        ),
    ]
