# Generated by Django 2.1.15 on 2021-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reses', '0005_ventareses'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='vendida',
            field=models.BooleanField(default=False),
        ),
    ]
