# Generated by Django 2.1.15 on 2021-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reses', '0006_res_vendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventareses',
            name='medio_pago',
            field=models.CharField(choices=[('transferencia bancaria', 'TRANSFERENCIA BANCARIA'), ('mercado pago', 'MERCADO PAGO'), ('efectivo', 'EFECTIVO'), ('tarjeta', 'TARJETA')], default='efectivo', max_length=15),
        ),
    ]
