# Generated by Django 2.1.15 on 2021-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(blank=True, choices=[('natural', 'natural'), ('juridica', 'juridica')], max_length=15, null=True),
        ),
    ]
