# Generated by Django 2.1.15 on 2021-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortes',
            name='codigo',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cortes',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
