# Generated by Django 2.1.15 on 2021-02-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0002_remove_vino_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vino.Bodega'),
        ),
        migrations.AlterField(
            model_name='vino',
            name='cepa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vino.Cepa'),
        ),
    ]
