# Generated by Django 2.1.15 on 2021-02-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vino', '0003_auto_20210201_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vino',
            options={'verbose_name': 'Productos'},
        ),
    ]
